### PR TITLE
Czech translation of interface.

### PR DESCRIPTION
**Pull request by MuadDib90**
@mgrinzPlayer Do you need to commit also the translations of addons to this repository?

Also, I have no idea, how to test anything I translated to this launcher or addons. I am lost as a squirrel...

### CODE REVIEW

**Comment by mgrinzPlayer** [comment]
Thank you.

> Also, I have no idea, how to test anything I translated to this launcher or addons. I am lost as a squirrel

1. pull https://github.com/Realm667/boa-addons to your PC
2. go inside source folder, make translations inside every addoninfo.txt for each addon, there are already some translations
3. execute add-on_builder.cmd
4. it will create release folder
5. get latest release of launcher from https://github.com/mgrinzPlayer/BoaLauncher/releases/latest
6. extract it to boa-addons release folder
7. the tree would be: `E:\GitHub\boa-addons\release>tree /f`
```
E:\GitHub\boa-addons\release
│   addon_8bitmusic.boa
│   addon_behaviour.boa
│   addon_disable_hints.boa
│   addon_efficiency.boa
│   addon_grenades_only.boa
│   addon_instagib.boa
│   addon_lowres_models.boa
│   addon_m2hb.boa
│   addon_melee.boa
│   addon_more_weapons.boa
│   addon_movement.boa
│   addon_score.boa
│   addon_vampire.boa
│   Blade of Agony - Launcher.exe
│
├───addons
│       8bitmusic.pk3
│       behaviour.pk3
│       disable_hints.pk3
│       efficiency.pk3
│       grenades_only.pk3
│       instagib.pk3
│       lowres_models.pk3
│       m2hb.pk3
│       melee.pk3
│       more_weapons.pk3
│       movement.pk3
│       score.pk3
│       vampire.pk3
│
└───language
        Blade of Agony - Launcher.de.po
        Blade of Agony - Launcher.pl.po
        Blade of Agony - Launcher.ru.po
```
8. place your translation of launcher interface to language folder
9. execute the launcher, it should automatically detect your system language
10. to force other interface language, just create shortcut to launcher and add this parameter (ru for Russian, de for German): `-launcher_lang ru`
or from command line: `"Blade of Agony - Launcher.exe" -launcher_lang ru`

obraz

**Comment by mgrinzPlayer** [comment]
For me it looks good. You can test it more with different screen resolutions, Windows scaling, etc.

On my machine it looks like this:
obraz

**Comment by mgrinzPlayer** [comment]
PS did you forget to translate "exit"?

**Comment by MuadDib90** [comment]
Wow, nice. Thanks man a lot! Will test it according to you.

Regarding "exit"; no, I did not forget. It is commonly used these days, so it is OK and also understandable. 👍

**Comment by MuadDib90** [comment]
I am stucked on executing "Blade of Agony - Launcher.exe", this file is nowhere to be found...
What I am doing wrong @mgrinzPlayer please?

**Comment by mgrinzPlayer** [comment]
> 5. get latest release of launcher from https://github.com/mgrinzPlayer/BoaLauncher/releases/latest

There is 7z archive.

**Comment by MuadDib90** [comment]
Nearly at the finish line to test addons. One last problem (I pray), I get this message (when try to execute the launcher):
obrazek
Do you happen to know, what the cause could be please?

**Comment by mgrinzPlayer** [comment]
This one appears when there's no boa.exe file.

**Comment by MuadDib90** [comment]
Ah, finally got a chance to test it all.
I should have all necessarily files from GZDoom built in that folder with Blade of Agony - Launcher.exe, and rename gzdoom.exe to boa.exe. I didn't know that.

Now it works. Thanks for helping through. ;-)

**Pull request merged**
